//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GizaWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int ID { get; set; }
        public int FILE_NUMBER { get; set; }
        public string NAME { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<System.DateTime> DATE_HIRED { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<int> INSURANCE_NUMBER { get; set; }
    }
}
