//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GizaWebsite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADDING_ENTITY_TYPE> ADDING_ENTITY_TYPE { get; set; }
        public DbSet<C_TYPE> C_TYPE { get; set; }
        public DbSet<CLOSET> CLOSETs { get; set; }
        public DbSet<COMPLAINT_TYPE> COMPLAINT_TYPE { get; set; }
        public DbSet<CORRESPONDENCE_IN> CORRESPONDENCE_IN { get; set; }
        public DbSet<CORRESPONDENCE_OUT> CORRESPONDENCE_OUT { get; set; }
        public DbSet<DOCUMENT_TYPE> DOCUMENT_TYPE { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public DbSet<ENTITY_TYPE> ENTITY_TYPE { get; set; }
        public DbSet<HOMEPAGE_CONTENT> HOMEPAGE_CONTENT { get; set; }
        public DbSet<IMPORTANCE> IMPORTANCEs { get; set; }
        public DbSet<REPLY_TYPE> REPLY_TYPE { get; set; }
        public DbSet<SHELF> SHELves { get; set; }
        public DbSet<STATUS> STATUS { get; set; }
        public DbSet<TOPIC_TYPE> TOPIC_TYPE { get; set; }
    }
}
